workflows:
  android_staging:
    name: Moto - Passenger Staging
    max_build_duration: 30
    instance_type: mac_mini_m1

    triggering:
      events:
      - push
      branch_patterns:
      - pattern: "staging"
      - include: true
      - source: true
      cancel_previous_builds: true

    environment:
      flutter: 3.32.2
      groups:
      - moto_staging
      android_signing:
      - moto_passenger_keystore

    scripts:
    - name: Set up local.properties
      script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

    - name: Get Flutter packages
      script: flutter pub get

    - name: Config definitions
      script: |
        cat > .env << EOF
        API_BASE_URL=$API_BASE_URL
        EOF
    - name: Build App Bundle
      script: flutter build appbundle --release

    artifacts:
    - build/**/outputs/**/*.aab
    - build/**/outputs/**/mapping.txt
    - flutter_drive.log

    publishing:
      email:
        recipients:
        - comercialpepiviagens@gmail.com
        notify:
          success: false
          failure: true

      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
        submit_as_draft: false
